### ISSUE TITLE
Consider move to JuliaAstro

### ISSUE THREAD

**Issue by mileslucas** [JuliaAstro/XPA.jl#3]
Hi! I was looking through your DS9.jl and this repo and was curious if you would consider moving them into the JuliaAstro organization? You would still have full repo owner access but it would provide more visibility. Let me know what you think!

**Comment by emmt** [comment]
Yes this would be a very good idea. Thank you for the proposition, let me know how I can do that.

**Comment by mileslucas** [comment]
Thanks, the transition should be relatively minor:
1. Add you to the JuliaAstro org (cc @giordano)
2. Now, in your repo settings there is a button under general at the bottom for transfer ownership, click that and choose JuliaAstro. By transferring to an organization, you don't actual lose your "owner" priveleges (and if something goes awry Mosè can help sort them out). 
3. The docs/etc. will start building under the JuliaAstro domain, so any code coverage, doc badges, links, etc. will all need their root domain changed. The JuliaAstro docs end up under `https://juliaastro.github.io/<Repo.jl>/`. Also any secrets will have to be transferred over (eg a documenter key) to the new repo settings (although they may transfer automatically, I'm not sure). Again, the transfer won't expose any secrets to anyone who doesn't already have those priveleges for your repos.

I'm happy to help along the way!

**Comment by giordano** [comment]
Invitation sent!

**Comment by emmt** [comment]
Many thanks to @mileslucas for detailed instructions and to @giordano for the invitation. I have transfered emmt/XPA.jl and emmt/DS9.jl to JuliaAstro. I have a question: should I check the boxes "tranfert to **contributors**", "... to **GSoC students**"?

**Comment by mileslucas** [comment]
Up to you. Transfer to contributors would let those folks have some of the access (merge, close, etc). I wouldn’t necessarily transfer to the GSoC students. If you want to still have full control only then don’t transfer anything.

**Comment by emmt** [comment]
OK I leave it as it is now. I can change later or add more specific persons.

**Comment by emmt** [comment]
@giordano: Following your instructions, I updated all URL's (for the doc., TravisCI, etc.) and verythings went fine. I did not have to do anything special for the Documenter key to have the docs autmatically built. I however have an issue: package XPA is no longer found by Julia's package manager.

**Comment by giordano** [comment]
> I however have an issue: package XPA is no longer found by Julia's package manager.

Transferring the repo should have created automatically a redirect to this one.  However I see that at https://github.com/emmt/XPA.jl there is a new repo.  You need to open a PR to the General registry to change the address in https://github.com/JuliaRegistries/General/blob/master/X/XPA/Package.toml

**Comment by mileslucas** [comment]
https://github.com/JuliaRegistries/General/pull/11592

**Comment by emmt** [comment]
I re-created a repository at https://github.com/emmt/XPA.jl to redirect people to  https://github.com/JuliaAstro/XPA.jl  but perhaps this was a bad idea (or there is better way to do that automatically). I open a PR as you suggested. That was easy, thanks!

**Comment by giordano** [comment]
> or there is better way to do that automatically

Yes: don't do anything :wink:

**Comment by emmt** [comment]
Ok but for people who previously `Pkg.add` with the old URL to keep inline with the master version, how can I make them informed that the URL has changed?

**Comment by giordano** [comment]
They'll just need to update the registry
